/// Flutter icons IcOverView
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IcOverView
///      fonts:
///       - asset: fonts/IcOverView.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IcOverView {
  IcOverView._();

  static const _kFontFam = 'IcOverView';
  static const String? _kFontPkg = null;

  static const IconData ic_overview = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
